#!/usr/bin/env bash
set -e

mamba update -n base -c conda-forge mamba libsolv -y || true

rm -rf /opt/conda/envs/r4-base

mamba env create -f /etc/mamba-envs/r4-base.yml

# Register conda's libs with the system linker so R always finds them
echo "/opt/conda/envs/r4-base/lib" > /etc/ld.so.conf.d/r4-base.conf
ldconfig

Rscript -e '.libPaths("/opt/conda/envs/r4-base/lib/R/library/"); devtools::install_github("satijalab/seurat-data")'